normas/urls.py
from django.urls import path
from . import views

app_name = 'normas'
urlpatterns = [
    path('', views.conectado, name='conectado'),
    path('fase1', views.fase1, name='fase1'),
    path('empresa/', views.empresa, name='empresa'),
    path('empresa/estrutura', views.empresa_estrutura, name='estrutura'),
    path('empresa/estrutura/diretoria', views.empresa_estrutura_diretoria, name='estrutura_diretoria'),
    path('empresa/estrutura/empresa', views.empresa_estrutura_empresa, name='estrutura_empresa'),
    path('empresa/estrutura/gerencia', views.empresa_estrutura_gerencia, name='estrutura_gerencia'),
    path('empresa/estrutura/divisao', views.empresa_estrutura_divisao, name='estrutura_divisao'),
    path('empresa/estrutura/areatrab', views.empresa_estrutura_areatrab, name='estrutura_areatrab'),
    path('empresa/estrutura/especializacao', views.empresa_estrutura_especializacao, name='estrutura_especializacao'),
    path('empresa/estrutura/funcao', views.empresa_estrutura_funcao, name='estrutura_funcao'),
    path('empresa/funcionario', views.empresa_funcionario, name='funcionario'),
    path('empresa/funcionario/cadastro', views.empresa_funcionario_cadastro, name='funcionario_cadastro'),
    path('atividade/', views.atividade, name='atividade'),
    path('atividade/atividade', views.atividade_atividade, name='atividade_atividade'),
    path('atividade/atividade/estrutura', views.atividade_atividade_estrutura, name='atividade_atividade_estrutura'),
    path('atividade/atividade/gerencia', views.atividade_atividade_gerencia, name='atividade_atividade_gerencia'),
    path('atividade/atividade/execucao', views.atividade_atividade_execucao, name='atividade_atividade_execucao'),
    path('atividade/atividade/atividade', views.atividade_atividade_atividade, name='atividade_atividade_atividade'),
    path('atividade/atividade/trabalho', views.atividade_atividade_trabalho, name='atividade_atividade_trabalho'),
    path('atividade/atividade/operacao', views.atividade_atividade_operacao, name='atividade_atividade_operacao'),
    path('atividade/atividade/tarefa', views.atividade_atividade_tarefa, name='atividade_atividade_tarefa'),
    path('normasprocedimentos/', views.normasprocedimentos, name='normasprocedimentos'),
    path('normasprocedimentos/normas', views.normasprocedimentos_normas, name='normasprocedimentos_normas'),
    path('normasprocedimentos/estudos', views.normasprocedimentos_estudos, name='normasprocedimentos_estudos'),
    path('normasprocedimentos/procedimentos', views.normasprocedimentos_procedimentos,
         name='normasprocedimentos_procedimentos'),
    path('normasprocedimentos/referencias', views.normasprocedimentos_referencias,
         name='normasprocedimentos_referencias'),
    path('normasprocedimentos/referencias/gerencia', views.normasprocedimentos_referencias_gerencia,
         name='normasprocedimentos_referencias_gerencia'),
    path('normasprocedimentos/referencias/atividade', views.normasprocedimentos_referencias_atividade,
         name='normasprocedimentos_referencias_atividade'),
    path('normasprocedimentos/referencias/operacao', views.normasprocedimentos_referencias_operacao,
         name='normasprocedimentos_referencias_operacao'),
    path('normasprocedimentos/referencias/tipo', views.normasprocedimentos_referencias_tipo,
         name='normasprocedimentos_referencias_tipo'),
    path('normasprocedimentos/referencias/assunto', views.normasprocedimentos_referencias_assunto,
         name='normasprocedimentos_referencias_assunto'),
    path('normasprocedimentos/referencias/glossario', views.normasprocedimentos_referencias_glossario,
         name='normasprocedimentos_referencias_glossario'),
    path('teste/', views.pdf_exceel_normas, name='pdf_exceel_normas'),
    path('exclui/', views.exclui_nivel1, name='exclui_nivel1'),
    path('get_nivel1/', views.get_nivel1, name='get_nivel1'),
]

somartech/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from normas.views import home, signup, activate, valida_usuario_gerente, change_password

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/', include('normas.urls')),
    path('cadastro/', signup, name='signup'),
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, {'next_page': '/login/'}, name='logout'),
    path('', home, name='home'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate,
        name='activate'),
    url(r'^valida/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', valida_usuario_gerente,
        name='valida_usuario_gerente'),
    
    url(r'^password/$', change_password, name='change_password'),
]

normas/models.py
from django.db import models
from django.contrib.auth.models import User


class CategoriaNorma(models.Model):
    nome_categoria = models.TextField(max_length=50)

    def __str__(self):
        return self.nome_categoria


class Documento(models.Model):
    nome_documento = models.TextField(max_length=50)

    def __str__(self):
        return self.nome_documento


class NormaPDF(models.Model):
    documentoFK = models.ForeignKey(Documento, on_delete=models.CASCADE)
    categoriaFK = models.ForeignKey(CategoriaNorma, on_delete=models.CASCADE)
    norma_paiFK = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    identificador = models.CharField(max_length=10)
    possui_subnorma = models.BooleanField()
    conteudo = models.TextField(max_length=500)

    def __str__(self):
        return str(self.documentoFK) + " - " + str(self.categoriaFK) + " - " + str(self.identificador) + "-"\
               + str(self.norma_paiFK) + "." + str(self.possui_subnorma) + " - " + str(self.conteudo)


class Empresa(models.Model):
    nome = models.CharField(max_length=50)
    codigo = models.IntegerField(default=0, unique=True)
    gerentePK = models.IntegerField(default=0)


class Funcionario(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)

normas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Empresa, Funcionario


class RequisitaNovoUsuario(forms.ModelForm):
    empresa = forms.CharField(max_length=10)
    first_name = forms.CharField(label="Primeiro Nome")
    last_name = forms.CharField(label="Sobrenome")
    empresa = forms.CharField(label="Código da empresa")
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'empresa')

normas/views.py
from .forms import RequisitaNovoUsuario
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.core.handlers.wsgi import WSGIRequest
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.crypto import get_random_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_text
from django.template.loader import render_to_string
from normas.tokens import account_activation_token
from normas.models import NormaPDF
from django.http import JsonResponse
from subprocess import Popen, PIPE, STDOUT

import json


def is_authenticated(user):
    return user.is_authenticated


def nivel_1(user):
    return user.groups.filter(name='nivel1').exists()


def nivel_2(user):
    return user.groups.filter(name='nivel2').exists()


def nivel_3(user):
    return user.groups.filter(name='nivel3').exists()


def nivel_logado(user):  # funcionario cadastrado
    return is_authenticated(user) and nivel_1(user)


def nive2_logado(user):  # gerente cadastrado
    return is_authenticated(user) and nivel_2(user)


def nive3_logado(user):  # adm do sistema
    return is_authenticated(user) and nivel_3(user)


def home(request):
    return render(request, 'normasPDF/home.html')


@user_passes_test(nivel_logado, login_url='/login/')
def conectado(request):
    return render(request, 'normasPDF/base.html')


@user_passes_test(nivel_logado, login_url='/login/')
def fase1(request):
    return render(request, 'normasPDF/fase1.html')


@user_passes_test(nivel_logado, login_url='/login/')
def empresa(request):
    # busca todas as empresas e retorna o nome dela
    empresas = {"nome_empresa": [["Empresa A", 55], ["Empresa B", 56]]}

    return render(request, 'normasPDF/empresa.html', {'empresas': empresas})


def get_nivel1(request):
    resultado = {}

    # falta verificar o nivel de segurança do usuário.
    # fazer a buscar no banco de dados para cada setor utilizando request.GET.get("data") como paramentro
    # resultado esperado para retorno {"nomesetor":[['id','nome'],['id',nome']]}
    if request.GET.get("tipo") == "empresa":
        resultado = {'empresas': [['01', 'Empresa H', 'Dono H'], ['02', 'Empresa J', 'Dono J']]}
    elif request.GET.get("tipo") == "diretoria":
        resultado = {'diretorias': [['01', 'Diretoria A', 'Diretor A'], ['02', 'Diretoria B', 'Diretor B']]}
    elif request.GET.get("tipo") == "gerencia":
        resultado = {'gerencias': [['014', 'Gerencia C', 'Gerente C'], ['015', 'Gerencia D', 'Gerente D']]}
    elif request.GET.get("tipo") == "divisao":
        resultado = {'divisoes': [['17', 'Divisão Q', 'Encarregado Q'], ['18', 'Divisão R', 'Encarregado QR']]}
    elif request.GET.get("tipo") == "areatrabalho":
        resultado = {'areatrabalhos': [['40', 'Área trabalho T'], ['40', 'Área trabalho U']]}
    elif request.GET.get("tipo") == "especialidade":
        resultado = {'especialidades': [['21', 'Programador'], ['22', 'Analista']]}
    elif request.GET.get("tipo") == "funcao":
        resultado = {'funcoes': [['21', 'X'], ['22', 'C']]}

    return JsonResponse(resultado)


def exclui_nivel1(request):
    try:
        # excluir no bd o dado passada no parametro
        resposta = "Setor excluido com sucesso."
    except:
        resposta = "Houve um problema na excluisão."
    return JsonResponse(resposta)


@user_passes_test(nivel_logado, login_url='/login/')
def empresa_estrutura(request):
    return render(request, 'normasPDF/empresa_estrutura.html')


@user_passes_test(nivel_logado, login_url='/login/')
def empresa_estrutura_empresa(request):
    conteudo = WSGIRequest({
        'REQUEST_METHOD': 'GET',
        'wsgi.input': {"tipo": "empresa"},
    })
    template = 'normasPDF/empresa_estrutura_empresa.html'

    return render(request, template, {'setor': json.loads(get_nivel1(conteudo).content), 'tipo': 'empresa'})


@user_passes_test(nivel_logado, login_url='/login/')
def empresa_estrutura_diretoria(request):
    conteudo = WSGIRequest({
        'REQUEST_METHOD': 'GET',
        'wsgi.input': {"tipo": "diretoria"},
    })
    template = 'normasPDF/empresa_estrutura_diretoria.html'

    return render(request, template, {'setor': json.loads(get_nivel1(conteudo).content), 'tipo': 'diretoria'})


@user_passes_test(nivel_logado, login_url='/login/')
def empresa_estrutura_gerencia(request):
    conteudo = WSGIRequest({
        'REQUEST_METHOD': 'GET',
        'wsgi.input': {"tipo": "gerencia"},
    })
    template = 'normasPDF/empresa_estrutura_gerencia.html'

    return render(request, template,
                  {'setor': json.loads(get_nivel1(conteudo).content), 'tipo': 'gerencia'})


@user_passes_test(nivel_logado, login_url='/login/')
def empresa_estrutura_divisao(request):
    conteudo = WSGIRequest({
        'REQUEST_METHOD': 'GET',
        'wsgi.input': {"tipo": "divisao"},
    })
    template = 'normasPDF/empresa_estrutura_divisao.html'

    return render(request, template,
                  {'setor': json.loads(get_nivel1(conteudo).content), 'tipo': 'divisao'})


@user_passes_test(nivel_logado, login_url='/login/')
def empresa_estrutura_areatrab(request):
    conteudo = WSGIRequest({
        'REQUEST_METHOD': 'GET',
        'wsgi.input': {"tipo": "areatrabalho"},
    })
    template = 'normasPDF/empresa_estrutura_areatrab.html'

    return render(request, template,
                  {'setor': json.loads(get_nivel1(conteudo).content), 'tipo': 'areatrabalho'})


@user_passes_test(nivel_logado, login_url='/login/')
def empresa_estrutura_especializacao(request):
    conteudo = WSGIRequest({
        'REQUEST_METHOD': 'GET',
        'wsgi.input': {"tipo": "especialidade"},
    })
    template = 'normasPDF/empresa_estrutura_especializacao.html'

    return render(request, template,
                  {'setor': json.loads(get_nivel1(conteudo).content), 'tipo': 'especialidade'})


@user_passes_test(nivel_logado, login_url='/login/')
def empresa_estrutura_funcao(request):
    conteudo = WSGIRequest({
        'REQUEST_METHOD': 'GET',
        'wsgi.input': {"tipo": "funcao"},
    })
    template = 'normasPDF/empresa_estrutura_funcao.html'

    return render(request, template, {'setor': json.loads(get_nivel1(conteudo).content), 'tipo': 'funcao'})


@user_passes_test(nivel_logado, login_url='/login/')
def empresa_funcionario(request):
    template = 'normasPDF/funcionario.html'
    return render(request, template)


@user_passes_test(nivel_logado, login_url='/login/')
def empresa_funcionario_cadastro(request):
    template = 'normasPDF/funcionario_cadastro.html'
    return render(request, template)


@user_passes_test(nivel_logado, login_url='/login/')
def atividade(request):
    template = 'normasPDF/atividade.html'
    empresas = {"nome_empresa": [["Empresa A", 55], ["Empresa B", 56]]}
    return render(request, template, {"empresa": empresas})


@user_passes_test(nivel_logado, login_url='/login/')
def atividade_atividade(request):
    template = 'normasPDF/atividade_atividade.html'
    return render(request, template)


@user_passes_test(nivel_logado, login_url='/login/')
def atividade_atividade_estrutura(request):
    template = 'normasPDF/atividade_atividade_estrutura.html'
    return render(request, template)


@user_passes_test(nivel_logado, login_url='/login/')
def atividade_atividade_gerencia(request):
    template = 'normasPDF/atividade_atividade_gerencia.html'
    return render(request, template)


@user_passes_test(nivel_logado, login_url='/login/')
def atividade_atividade_execucao(request):
    template = 'normasPDF/atividade_atividade_execucao.html'
    return render(request, template)


@user_passes_test(nivel_logado, login_url='/login/')
def atividade_atividade_atividade(request):
    template = 'normasPDF/atividade_atividade_atividade.html'
    return render(request, template)


@user_passes_test(nivel_logado, login_url='/login/')
def atividade_atividade_trabalho(request):
    template = 'normasPDF/atividade_atividade_trabalho.html'
    return render(request, template)


@user_passes_test(nivel_logado, login_url='/login/')
def atividade_atividade_operacao(request):
    template = 'normasPDF/atividade_atividade_operacao.html'
    return render(request, template)


@user_passes_test(nivel_logado, login_url='/login/')
def atividade_atividade_tarefa(request):
    template = 'normasPDF/atividade_atividade_tarefa.html'
    return render(request, template)


@user_passes_test(nivel_logado, login_url='/login/')
def normasprocedimentos(request):
    template = "normasPDF/normasprocedimentos.html"

    return render(request, template)


@user_passes_test(nivel_logado, login_url='/login/')
def normasprocedimentos_normas(request):
    template = 'normasPDF/normasprocedimentos_normas.html'
    try:
        queryfromdatabase = NormaPDF.objects.all()
        resposta = ""
    except:  # especificar o except. falha ao conectar ao banco de dados
        resposta = "Falha ao comuniar com o banco de dados"
    return render(request, template, {'resultado': queryfromdatabase, 'sucesso': resposta})


@user_passes_test(nivel_logado, login_url='/login/')
def normasprocedimentos_procedimentos(request):
    template = 'normasPDF/normasprocedimentos_procedimentos.html'

    return render(request, template)


@user_passes_test(nivel_logado, login_url='/login/')
def normasprocedimentos_estudos(request):
    template = 'normasPDF/normasprocedimentos_estudos.html'

    return render(request, template)


@user_passes_test(nivel_logado, login_url='/login/')
def normasprocedimentos_referencias(request):
    template = 'normasPDF/normasprocedimentos_referencias.html'

normas/templates/normasPDF/atividade_atividade.html
{% block extensao %}
<style>
    .margintop{margin-top:10px;}

</style>
<div>
    {% include "normasPDF/categorias_atividade.html" %}
</div>
<div class="margintop" style="background-color:lightgray;padding:2px;">
    <button id="atividade_estrutura">Estrut. Organiz.</button>
    <button id="atividade_gerencia">1. Etapa de Gerencia</button>
    <button id="atividade_execucao">2. Fase de Execução</button>
    <button id="atividade_atividade">3. Atividade</button>
    <button id="atividade_trabalho">4. Etapa de Trabalho</button>
    <button id="atividade_operacao">5. Operação.</button>
    <button id="atividade_tarefa">6. Tarefa</button>
</div>
<div id="atividade_extensao" style="background-color:gray;padding:10px;">
    {% block estrututra_extensao %}
    {% endblock %}
</div>
<script>
    $(document).ready(function(){
        $("#atividade_estrutura").click(function(){
            $("#atividade_extensao").load("/base/atividade/atividade/estrutura");
        });
        $("#atividade_gerencia").click(function(){
            $("#atividade_extensao").load("/base/atividade/atividade/gerencia");
        });
        $("#atividade_execucao").click(function(){
            $("#atividade_extensao").load("/base/atividade/atividade/execucao");
        });
        $("#atividade_atividade").click(function(){
            $("#atividade_extensao").load("/base/atividade/atividade/atividade");
        });
        $("#atividade_trabalho").click(function(){
            $("#atividade_extensao").load("/base/atividade/atividade/trabalho");
        });
        $("#atividade_operacao").click(function(){
            $("#atividade_extensao").load("/base/atividade/atividade/operacao");
        });
        $("#atividade_tarefa").click(function(){
            $("#atividade_extensao").load("/base/atividade/atividade/tarefa");
        });
    });

</script>
{% endblock %}

normas/templates/normasPDF/atividade_atividade_execucao.html
{% block estrutura_extensao %}
<style>
    .inlineblock{display:inlineblock;}
    table, th, td {border: 1px solid black;}
</style>
<p style="font-size:30px;">Fase Execução</p>
<div class="inlineblock" style="vertical-align:top;">
    <div class="inlineblock">
        Ref.
        <br>
        <input type="text"style="width:50px;">
    </div>
    <div class="inlineblock">
        Cod.
        <br>
        <input type="text"style="width:50px;">
    </div>
    <div class="inlineblock">
        Fase de Execução
        <br>
        <input type="text" style="width:250px;">
    </div>

    <table style="heigth:100px;overflow-y:scroll;margin-top:10px;">
        <tr>
            <th style="width:50px;">Ref</th>
            <th style="width:50px;">Cod.</th>
            <th style="width:250px;">Titulo</th>
        </tr>
        {% for i in dado %}
        <tr>
            <td>{{i.0}}</td>
            <td>{{i.1}}</td>
            <td>{{i.2}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div class="inlineblock" style="width:50%;" >
    Nota Técnica
    <br>
    <input type="text" style="width:100%;height:100px;">
</div>
{% endblock %}

normas/templates/normasPDF/categorias.html
{% block categoria %}
<style>
    .botao{height:5px;width:5px;}
    .largura{min-width:200px;}
    .box2{width:50px;height:20px;}


</style>
<div style="background-color: gray; padding: 10px;">
    <div class="inlineblock">
        <div class="inlineblock" style="text-align:right;">
            Empresa:
            <button class="botao"></button>
            <br>
            Diretoria:
            <button class="botao"></button>
            <br>
            Gerencia:
            <button class="botao"></button>
            <br>
        </div>
        <div class="inlineblock">
            <select id="id_empresa" class="largura">
                <option disabled selected></option>
                {% for empresa in empresas.nome_empresa %}
                <option value="{{empresa.1}}">{{empresa.0}}</option>
                {% endfor %}
            </select><br>
            <select id="id_diretoria" class="largura" disabled></select><br>
            <select id="id_gerencia" class="largura" disabled></select><br>
        </div>
    </div>
    <div class="inlineblock">
        <div class="inlineblock" style="text-align:right;">
            Divisão:
            <button class="botao"></button>
            <br>
            Área de Trabalho:
            <button class="botao"></button>
            <br>
            Especialidades:
            <button class="botao"></button>
            <br>
        </div>
        <div class="inlineblock">
            <select id="id_divisao" class="largura" disabled></select><br>
            <select id="id_areatrab" class="largura" disabled></select><br>
            <select id="id_especialidade" class="largura" disabled></select><br>
        </div>
        <div class="inlineblock">
            <input id="id_divisao2" class="box2" disabled><br>
            <input id="id_areatrab2" class="box2" disabled><br>
            <input id="id_especialidade2" class="box2" disabled><br>
        </div>
    </div>
    <div class="inlineblock">
        <div class="inlineblock">
            Código
            <br>
            Empresa/Diret./Gerência
            <input type="text" style="height:20px;" >
            <br>
            Div./Area Trab./Especial.
            <input type="text" style="height:20px;">
        </div>
        <div class="inlineblock" style="vertical-align:top;">
            <button>ok</button>
            <br>
            <button>^</button>
        </div>
    </div>
</div>
{% block inner_js %}
<script type="text/javascript">
    $(document).ready(function(){
    $("#id_empresa").change(function () {
        console.log("empresa");
        $("#id_cod_empresa").val($("#id_empresa option:selected").val());
        $("#id_diretoria").empty().append("<option disabled SELECTED></option>").prop("disabled", false);
        $("#id_gerencia").empty().prop("disabled", true);
        $("#id_divisao").empty().prop("disabled", true);
        $("#id_areatrab").empty().prop("disabled", true);
        $("#id_especialidade").empty().prop("disabled", true);
        $.get("/base/get_nivel1/",{data:$("#id_empresa option:selected").val(),tipo:"diretoria"},function(resultado){
            $.each(resultado.diretorias, function(index, value){
                $("#id_diretoria").append(new Option(value[1], value));
            });
        });
    });
    $("#id_diretoria").change(function () {
        console.log("id_diretoria. change");
        $("#id_gerencia").empty().append("<option disabled SELECTED></option>").prop("disabled", false);
        $("#id_divisao").empty().prop("disabled", true);
        $("#id_areatrab").empty().prop("disabled", true);
        $("#id_especialidade").empty().prop("disabled", true);
        $.get("/base/get_nivel1/",{data:$("#id_diretoria option:selected").val(),tipo:"gerencia"},function(resultado){
            $.each(resultado.gerencias, function(index, value){
                $("#id_gerencia").append(new Option(value[1]));
            });
        });
    });
    $("#id_gerencia").change(function () {
        $("#id_divisao").empty().append("<option disabled SELECTED></option>").prop("disabled", false);
        $("#id_areatrab").empty().prop("disabled", true);
        $("#id_especialidade").empty().prop("disabled", true);
        $.get("/base/get_nivel1/",{data:$("#id_gerencia option:selected").val(),tipo:"divisao"},function(resultado){
            $.each(resultado.divisoes, function(index, value){
                $("#id_divisao").append(new Option(value[1]));
            });
        });
    });
    $("#id_divisao").change(function () {
        $("#id_areatrab").empty().append("<option disabled SELECTED></option>").prop("disabled", false);
        $("#id_especialidade").empty().prop("disabled", true);
        $.get("/base/get_nivel1/",{data:$("#id_divisao option:selected").val(),tipo:"areatrabalho"},function(resultado){
            $.each(resultado.areatrabalhos, function(index, value){
                $("#id_areatrab").append(new Option(value[1]));
            });
        });
    });
    $("#id_areatrab").change(function () {
        $("#id_especialidade").empty().append("<option disabled SELECTED></option>").prop("disabled", false);
        $.get("/base/get_nivel1/",{data:$("#id_areatrab option:selected").val(),tipo:"especialidade"},function(resultado){
            $.each(resultado.especialidades, function(index, value){
                $("#id_especialidade").append(new Option(value[1]));
            });
        });
    });
});


</script>
{% endblock inner_js %}
{% endblock %}

normas/templates/normasPDF/empresa.html
{% extends "normasPDF/fase1.html" %}
{% block conectado %}
<style>
    .a {width: 100%;}
    .b{width: 150px;background-color: gray;padding:5px;height:500px;}
    .inlineblock{display:inline-block;}
    .margintop{margin-top:10px;}
</style>
<div>
    <div class="b inlineblock">
        <button class=" a" id="edificios">Edificios</button>
        <button class=" a" id="estrutura">EO - Estrut. Organiz.</button>
        <button class=" a margintop" id="contratos">Contratos</button>
        <button class=" a margintop" id="projetos">Projetos</button>
        <button class=" a" id="estudos">Estudos de riscos</button>
        <button class=" a margintop" id="estrategias">Estratégias de SMS</button>
        <button class=" a margintop" id="equipes">Equipes de Trabalho</button>
        <button class=" a" id="funcionarios">Funcionários</button>
    </div>
    <div class="inlineblock" style="width: 84%;vertical-align:top; ">
        <div>
            {% include "normasPDF/categorias.html" with empresas=empresas %}
        </div>
        <div style=";background-color: gray;margin-top: 10px;" id="extensao"></div>
    </div>
</div>
{% block inner_js %}
<script type="text/javascript">
    $(document).ready(function(){
    $("#estrutura").click(function(){
        $("#extensao").load("/base/empresa/estrutura");
    });
    $("#funcionarios").click(function(){
        $("#extensao").load("/base/empresa/funcionario");
    });
});
</script>
{% endblock inner_js %}
{% endblock %}

normas/templates/normasPDF/empresa_estrutura.html
<Style>
    .altura_botao{height:25px;}
</Style>
<div style="background-color: DarkGray;padding: 2px;">
    <button  id="estrutura_empresa">Empresa </button>
    <button  id="estrutura_diretoria">Diretoria</button>
    <button  id="estrutura_gerencia">Gerencias</button>
    <button  id="estrutura_divisao">Divisões</button>
    <button  id="estrutura_areatrabalho">Áreas de Trabalho</button>
    <button  id="estrutura_especialidade">Especialidades</button>
    <button  id="estrutura_funcao">Funções</button>
</div>
<div style="min-height: 350px;padding:10px;overflow:auto;" id="estrutura_extensao"></div>

{% block inner_js_estrutura %}
<script type="text/javascript">
    $(document).ready(function(){
    $("#estrutura_empresa").click(function(){
        console.log("estrutura_empresa.click");
        $("#estrutura_extensao").load("/base/empresa/estrutura/empresa");
    });
    $("#estrutura_diretoria").click(function(){
        $("#estrutura_extensao").load("/base/empresa/estrutura/diretoria" , {data:$("#id_empresa").val()});
    });
    $("#estrutura_gerencia").click(function(){
        $("#estrutura_extensao").load("/base/empresa/estrutura/gerencia", {data:$("#id_diretoria").val()});
    });
    $("#estrutura_divisao").click(function(){
        $("#estrutura_extensao").load("/base/empresa/estrutura/divisao", {data:$("#id_gerencia").val()});
    });
    $("#estrutura_areatrabalho").click(function(){
        $("#estrutura_extensao").load("/base/empresa/estrutura/areatrab", {data:$("#id_divisao").val()});
    });
    $("#estrutura_especialidade").click(function(){
        $("#estrutura_extensao").load("/base/empresa/estrutura/especializacao", {data:$("#id_areatrab").val()});
    });
    $("#estrutura_funcao").click(function(){
        $("#estrutura_extensao").load("/base/empresa/estrutura/funcao", {data:$("#id_especialidade").val()});
    });
});

</script>
{% endblock inner_js_estrutura %}